import Head from "next/head";
import Image from "next/image";
import { Nav, Navbar, Container } from "react-bootstrap";

export default function Retreats() {
	return (
		<div className="d-flex flex-column vh-100">
			<Head>
				<title>Create Next App!!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:ital@1&family=Nunito&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<Navbar bg="light" expand="lg">
				<Container fluid>
					<Navbar.Brand href="/">New Dawn Retreats</Navbar.Brand>
					<Navbar.Toggle aria-controls="basic-navbar-nav" />
					<Navbar.Collapse id="basic-navbar-nav">
						<Nav className="me-auto">
							<Nav.Link href="/retreats">Retreats</Nav.Link>
							<Nav.Link href="/about">About</Nav.Link>
							<Nav.Link href="/contact">Contact</Nav.Link>
						</Nav>
					</Navbar.Collapse>
				</Container>
			</Navbar>

			<main className="container-fluid pr-0 mt-4">
				<div class="row text-center">
					<div class="contourBtm pb-5">
						<h1>Upcoming Retreats</h1>
						<h3 class="my-2">~Sacred Rest & Restorative Experiences~</h3>
					</div>
				</div>
				<div class="row text-center align-items-center contourBtm">
					<div class="col-lg-7 pb-5 py-lg-5 px-0">
						<img src="/sunset3.jpg" alt="" class="img-fluid" />
					</div>
					<div class="col-lg-5 px-5 py-lg-5 pb-5 text-centered">
						<h3 class="my-0">Summerlake Hotsprings Retreat Autumn 2022</h3>
						<p class="my-0 my-3">
							More information for this retreat coming soon!
						</p>
						<a href="/retreats/summer_lake" class="btn pinkBtn btn-lg">
							View Details
						</a>
					</div>
				</div>

				<div class="row text-center align-items-center">
					<div class="col-lg-5 px-5 py-lg-5 pb-5 text-centered order-2 order-lg-1">
						<h3 class="my-0">Sacred Rest Mexico 2022</h3>
						<p class="my-0 my-3">
							More information for this retreat coming soon!
						</p>
						{/* <a href="/retreats/mexico" class="btn pinkBtn btn-lg">View Details</a> */}
					</div>

					<div class="col-lg-7 px-0 pb-5 py-lg-5 order-1 order-lg-2">
						<img
							src="https://images.unsplash.com/photo-1611222566360-ef1f0a8c6451?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bWV4aWNvJTIwYmVhY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
							alt=""
							class="img-fluid"
						/>
					</div>
				</div>
			</main>
			<footer class="footer py-3 mt-auto contourTop">
				<div class=" container-fluid">
					<div class="row">
						<div class="col-4 text-center btn copyright">
							<span class="text-muted">New Dawn Retreats 2022</span>
						</div>
						<div class="col-4 text-center">
							<a
								href="https://www.instagram.com/newdawnretreats/"
								class="btn text-muted">
								<i class="bi bi-instagram"> New Dawn Retreats</i>
							</a>
						</div>
						<div class="col-4 text-center">
							<a href="mailto:jnlcarter5@gmail.com" class="btn text-muted mail">
								Website developed by Nathan Carter
							</a>
						</div>
					</div>
				</div>
			</footer>
		</div>
	);
}
