import Head from "next/head";
import Image from "next/image";
import { Nav, Navbar, Container } from "react-bootstrap";

export default function Home() {
	return (
		<div className="d-flex flex-column vh-100">
			<Head>
				<title>New Dawn Retreats</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:ital@1&family=Nunito&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<Navbar bg="light" expand="lg">
				<Container fluid>
					<Navbar.Brand href="/">New Dawn Retreats</Navbar.Brand>
					<Navbar.Toggle aria-controls="basic-navbar-nav" />
					<Navbar.Collapse id="basic-navbar-nav">
						<Nav className="me-auto">
							<Nav.Link href="/retreats">Retreats</Nav.Link>
							<Nav.Link href="/about">About</Nav.Link>
							<Nav.Link href="/contact">Contact</Nav.Link>
						</Nav>
					</Navbar.Collapse>
				</Container>
			</Navbar>

			<main className="container-fluid pr-0 mt-4">
				<div className="row text-center">
					<div className="contourBtm pb-5">
						<h1 className="my-0">Summer Lake Hot Springs Retreat</h1>
						<h2 className="mt-2">~Sacred Rest~</h2>
					</div>
				</div>
				<div className="row text-center align-items-center contourBtm">
					<div className="col-md-7 py-md-5 px-0">
						<img src="/sunset1.jpg" alt="" className="img-fluid" />
					</div>
					<div className="col-md-5 px-5 py-5 text-centered">
						<p className="my-0">
							Come home to yourself by joining us in the ancient healing waters
							of Oregon's beautiful high plains desert. You can enjoy the
							natural outdoor hot springs in a spirit of connection and
							self-healing with other women of like-minded soul community.
						</p>
					</div>
				</div>

				<div className="row text-center align-items-center">
					<div className="col-md-5 px-5 py-md-5 py-5 text-centered order-2 order-md-1">
						<p className="my-0">
							Enjoy guided daily meditations with an emphasis on self-discovery.
							Embark on daily excursions to ancient caves and historical
							pictographs. Relish a healthy nightly meal prepared with love as a
							time to gather and connect and share. You can expect fire
							ceremonies, healing circles, drumming, sound therapy, and card
							readings. The sacred water is accessible 24/7. Massages will be
							available on-site with advanced bookings.
						</p>
					</div>

					<div className="col-md-7 px-0 py-md-5 order-1 order-md-2">
						<img src="/sunset3.jpg" alt="" className="img-fluid" />
					</div>
				</div>

				<div className="row">
					<div className="col-8 offset-2 text-center">
						<a href="/retreats" className="btn pinkBtn btn-lg mb-5">
							View Upcoming Retreats
						</a>
					</div>
				</div>
			</main>
			<footer className="footer py-3 mt-auto contourTop">
				<div className="footDiv text-center">
					<span className="text-muted">©New Dawn Retreats 2022</span>
				</div>
				<div className="footDiv text-center">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="20"
						height="20"
						fill="currentColor"
						viewBox="0 0 16 16">
						<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
					</svg>{" "}
					<i>
						<a
							href="https://www.instagram.com/newdawnretreats/"
							className="text-muted">
							New Dawn Retreats
						</a>
					</i>
				</div>
				<div className="footDiv text-center">
					<a href="mailto:jnlcarter5@gmail.com" className="text-muted">
						Website developed by Nathan Carter
					</a>
				</div>
			</footer>
		</div>
	);
}
