import Head from "next/head";
import Image from "next/image";
import { Nav, Navbar, Container } from "react-bootstrap";

export default function Home() {
	return (
		<div className="d-flex flex-column vh-100">
			<Head>
				<title>Create Next App!!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:ital@1&family=Nunito&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<Navbar bg="light" expand="lg">
				<Container fluid>
					<Navbar.Brand href="/">New Dawn Retreats</Navbar.Brand>
					<Navbar.Toggle aria-controls="basic-navbar-nav" />
					<Navbar.Collapse id="basic-navbar-nav">
						<Nav className="me-auto">
							<Nav.Link href="/retreats">Retreats</Nav.Link>
							<Nav.Link href="/about">About</Nav.Link>
							<Nav.Link href="/contact">Contact</Nav.Link>
						</Nav>
					</Navbar.Collapse>
				</Container>
			</Navbar>

			<main className="container-fluid pr-0 mt-4">
				<div class="row text-center">
					<div class="contourBtm pb-5">
						<h1 class="my-0">Summer Lake Hot Springs Retreat</h1>
						<h2 class="mt-2">~Sacred Rest~</h2>
					</div>
				</div>
				<div class="row text-center align-items-center contourBtm">
					<div class="col-md-7 py-md-5 px-0">
						<img src="/sunset1.jpg" alt="" class="img-fluid" />
					</div>
					<div class="col-md-5 px-5 py-5 text-centered">
						<p class="my-0">
							Come home to yourself by joining us in the ancient healing waters
							of Oregon's beautiful high plains desert. You can enjoy the
							natural outdoor hot springs in a spirit of connection and
							self-healing with other women of like-minded soul community.
						</p>
					</div>
				</div>

				<div class="row text-center align-items-center">
					<div class="col-md-5 px-5 py-md-5 py-5 text-centered order-2 order-md-1">
						<p class="my-0">
							Enjoy guided daily meditations with an emphasis on self-discovery.
							Embark on daily excursions to ancient caves and historical
							pictographs. Relish a healthy nightly meal prepared with love as a
							time to gather and connect and share. You can expect fire
							ceremonies, healing circles, drumming, sound therapy, and card
							readings. The sacred water is accessible 24/7. Massages will be
							available on-site with advanced bookings.
						</p>
					</div>

					<div class="col-md-7 px-0 py-md-5 order-1 order-md-2">
						<img src="/sunset3.jpg" alt="" class="img-fluid" />
					</div>
				</div>

				<div class="row">
					<div class="col-8 offset-2 text-center">
						<a href="/retreats" class="btn pinkBtn btn-lg mb-5">
							View Upcoming Retreats
						</a>
					</div>
				</div>
			</main>
			<footer class="footer py-3 mt-auto contourTop">
				<div class=" container-fluid">
					<div class="row">
						<div class="col-4 text-center btn copyright">
							<span class="text-muted">New Dawn Retreats 2022</span>
						</div>
						<div class="col-4 text-center">
							<a
								href="https://www.instagram.com/newdawnretreats/"
								class="btn text-muted">
								<i class="bi bi-instagram"> New Dawn Retreats</i>
							</a>
						</div>
						<div class="col-4 text-center">
							<a href="mailto:jnlcarter5@gmail.com" class="btn text-muted mail">
								Website developed by Nathan Carter
							</a>
						</div>
					</div>
				</div>
			</footer>
		</div>
	);
}
